# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/naren', '.']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/naren'] '''
 steps:
 # Build the container image
# - name: 'gcr.io/cloud-builders/docker'
  # args: ['build', '-t', 'gcr.io/$PROJECT_ID/chandra-dep:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 #- name: 'gcr.io/cloud-builders/docker'
  # args: ['push', 'gcr.io/$PROJECT_ID/chandra-dep:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'chandra-dep'
   - '--image'
   #- 'gcr.io/$PROJECT_ID/chandra-dep:$COMMIT_SHA'
   #- us-docker.pkg.dev/
   - '--region'
   - 'us-central1'
 images:
 #- 'gcr.io/$PROJECT_ID/chandra-dep:$COMMIT_SHA'
   - 'us-docker.pkg.dev/cloudrun/container/hello'
